In [29]:
#Problem Statement: What will be the number of air passengers when the marketing cost = $4500K

import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm

air_passengers = pd.read_csv('air_passengers.csv')

air_passengers.head()

air_passengers.info()

air_passengers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Passengers_count          263 non-null    int64
 1   marketing_cost            263 non-null    float64
 2   percent_delayed_flights   263 non-null    float64
 3   number_of_trips           263 non-null    int64
 4   customer_ratings          263 non-null    int64
 5   poor_weather_index        263 non-null    float64
 6   percent_male_customers    263 non-null    int64
 7   Holiday_week              263 non-null    int64
 8   percent_female_customers  263 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 18.6 KB

,Passengers_count,marketing_cost,percent_delayed_flights,number_of_trips,customer_ratings,poor_weather_index,percent_male_customers,Holiday_week,percent_female_customers
count,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000
mean,28865.581749,3705.558175,0.237643,1386.338403,6.992395,0.238821,44.638783,0.038023,54.839544
std,5579.293117,761.549485,0.079150,393.210697,1.994252,0.082641,8.815904,0.191616,8.833267
min,17591.000000,1902.200000,0.080000,703.000000,4.000000,0.060000,30.000000,0.000000,39.000000
25%,24906.000000,3144.350000,0.170000,1021.500000,5.000000,0.170000,37.000000,0.000000,47.900000
50%,28426.000000,3695.600000,0.230000,1456.000000,7.000000,0.240000,44.000000,0.000000,55.200000
75%,31611.500000,4180.350000,0.310000,1727.000000,9.000000,0.300000,52.000000,0.000000,62.150000
max,45899.000000,5753.500000,0.420000,1989.000000,10.000000,0.440000,60.000000,1.000000,69.700000

In [34]:
# y axis ~ x axis
model1 = sm.ols(formula='Passengers_count ~ marketing_cost', data=air_passengers)

fitted1 = model1.fit()
fitted1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:       Passengers_count   R-squared:                       0.761
Model:                            OLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     830.0
Date:                Sun, 18 Jan 2026   Prob (F-statistic):           4.87e-83
Time:                        16:42:51   Log-Likelihood:                -2453.4
No. Observations:                 263   AIC:                             4911.
Df Residuals:                     261   BIC:                             4918.
Df Model:                           1
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       5186.6868    839.019      6.182      0.000    3534.579    6838.795
marketing_cost     6.3901      0.222     28.810      0.000       5.953       6.827
==============================================================================
Omnibus:                        8.874   Durbin-Watson:                   1.829
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                9.679
Skew:                           0.342   Prob(JB):                      0.00791
Kurtosis:                       3.644   Cond. No.                     1.88e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.88e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:

#no of passengers were expecting when marketing cost is 4500K
new_data = pd.DataFrame({'marketing_cost':[4500]})
print(fitted1.predict(new_data))

0    33942.146091
dtype: float64

In [48]:
# predictions

air_passengers['passengers_count_predicted'] = round(fitted1.predict(air_passengers))

keep_cols = ["marketing_cost", "Passengers_count", "passengers_count_predicted"]

air_passengers[keep_cols]

air_passengers.columns

Index(['Passengers_count', 'marketing_cost', 'percent_delayed_flights',
       'number_of_trips', 'customer_ratings', 'poor_weather_index',
       'percent_male_customers', 'Holiday_week', 'percent_female_customers',
       'passengers_count_predicted'],
      dtype='object')

In [35]:
# vs customer_ratings
model2 = sm.ols(formula='Passengers_count ~ customer_ratings', data=air_passengers)

fitted2 = model2.fit()
fitted2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:       Passengers_count   R-squared:                       0.102
Model:                            OLS   Adj. R-squared:                  0.099
Method:                 Least Squares   F-statistic:                     29.72
Date:                Sun, 18 Jan 2026   Prob (F-statistic):           1.16e-07
Time:                        16:43:54   Log-Likelihood:                -2627.4
No. Observations:                 263   AIC:                             5259.
Df Residuals:                     261   BIC:                             5266.
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept         2.261e+04   1192.915     18.955      0.000    2.03e+04     2.5e+04
customer_ratings   894.4643    164.083      5.451      0.000     571.369    1217.560
==============================================================================
Omnibus:                       28.234   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               35.541
Skew:                           0.767   Prob(JB):                     1.92e-08
Kurtosis:                       3.944   Cond. No.                         27.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# inference: coffecient of R square = 0.102 when modeled with customer_ratings
# vs 0.761 when modeled with marketing_cost
# 76.1 % variation in number of passengers can be explained by marketing_cost
# only 10.2 % variation in number of passengers can be explained by customer_ratings

In [ ]:
#multiple linear regression
# air_passengers.columns
model3 = sm.ols(formula='Passengers_count ~ marketing_cost+customer_ratings +percent_delayed_flights + number_of_trips + poor_weather_index +percent_male_customers + Holiday_week + percent_female_customers'
                        , data=air_passengers)
fitted3 = model3.fit()
fitted3.summary()

#coeff of r squar is 0.911 which mean 91.1 % variation in number of passengers can be explained by all the independent variables together

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:       Passengers_count   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     325.3
Date:                Sun, 18 Jan 2026   Prob (F-statistic):          8.93e-129
Time:                        17:50:20   Log-Likelihood:                -2323.3
No. Observations:                 263   AIC:                             4665.
Df Residuals:                     254   BIC:                             4697.
Df Model:                           8
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                 4173.3041   3.71e+04      0.113      0.910   -6.88e+04    7.71e+04
marketing_cost               4.4279      0.168     26.287      0.000       4.096       4.760
customer_ratings           546.3104     53.897     10.136      0.000     440.168     652.453
percent_delayed_flights   2.187e+04   4827.398      4.530      0.000    1.24e+04    3.14e+04
number_of_trips              0.3004      0.270      1.114      0.266      -0.231       0.831
poor_weather_index        -919.5035   4520.130     -0.203      0.839   -9821.210    7982.203
percent_male_customers      -7.3113    372.653     -0.020      0.984    -741.195     726.572
Holiday_week              6804.5389    598.471     11.370      0.000    5625.942    7983.136
percent_female_customers   -15.7188    371.808     -0.042      0.966    -747.937     716.499
==============================================================================
Omnibus:                        0.087   Durbin-Watson:                   1.778
Prob(Omnibus):                  0.957   Jarque-Bera (JB):                0.082
Skew:                           0.041   Prob(JB):                        0.960
Kurtosis:                       2.969   Cond. No.                     1.43e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [51]:
air_passengers.head()

# air_passengers.columns

,Passengers_count,marketing_cost,percent_delayed_flights,number_of_trips,customer_ratings,poor_weather_index,percent_male_customers,Holiday_week,percent_female_customers,passengers_count_predicted
0,23291,3588.1,0.21,1503,5,0.19,38,0,61.2,28115.0
1,25523,3186.3,0.20,1881,6,0.22,35,0,64.4,25547.0
2,25620,3342.0,0.27,1850,7,0.27,51,0,48.0,26542.0
3,19625,2512.5,0.18,1295,8,0.19,37,0,62.6,21242.0
4,27231,3012.1,0.23,1100,9,0.24,38,0,61.2,24434.0

In [53]:
# multicollinearity check - having too many independent variables can be a curse

# VIF calculation function

def vif_cal(x_vars):
    xvar_names = x_vars.columns
    for i in range(0,xvar_names.shape[0]):
        y = x_vars[xvar_names[i]]
        x = x_vars[xvar_names.drop(xvar_names[i])]
        rsq = sm.ols(formula='y ~ x', data=x_vars).fit().rsquared
        vif = round(1/(1 - rsq),2)
        print (xvar_names[i], " VIF =  ", vif)

vif_cal(x_vars=air_passengers.drop(['Passengers_count','passengers_count_predicted'], axis=1))

marketing_cost  VIF =   1.51
percent_delayed_flights  VIF =   13.4
number_of_trips  VIF =   1.03
customer_ratings  VIF =   1.06
poor_weather_index  VIF =   12.81
percent_male_customers  VIF =   990.52
Holiday_week  VIF =   1.21
percent_female_customers  VIF =   989.91

In [55]:
# Dropping variables with high VIF one by one and recalculating VIFs

vif_cal(x_vars=air_passengers.drop(['Passengers_count','passengers_count_predicted','percent_male_customers'], axis=1))

marketing_cost  VIF =   1.51
percent_delayed_flights  VIF =   13.34
number_of_trips  VIF =   1.03
customer_ratings  VIF =   1.06
poor_weather_index  VIF =   12.78
Holiday_week  VIF =   1.2
percent_female_customers  VIF =   1.03

In [56]:
# Dropping variables with high VIF one by one and recalculating VIFs

vif_cal(x_vars=air_passengers.drop(['Passengers_count','passengers_count_predicted','percent_male_customers','percent_delayed_flights'], axis=1))

marketing_cost  VIF =   1.45
number_of_trips  VIF =   1.02
customer_ratings  VIF =   1.06
poor_weather_index  VIF =   1.25
Holiday_week  VIF =   1.2
percent_female_customers  VIF =   1.01

In [ ]:
# model after removing variables with high VIF
model_final = sm.ols(formula='Passengers_count ~ marketing_cost + customer_ratings + number_of_trips + poor_weather_index + Holiday_week + percent_female_customers',data=air_passengers)
fitted_final = model_final.fit()
fitted_final.summary()

#r square dropped from 0.911 to 0.904 after removing two variables with high VIF, so we can go ahead with this model

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:       Passengers_count   R-squared:                       0.904
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     401.2
Date:                Sun, 18 Jan 2026   Prob (F-statistic):          4.35e-127
Time:                        18:51:41   Log-Likelihood:                -2333.5
No. Observations:                 263   AIC:                             4681.
Df Residuals:                     256   BIC:                             4706.
Df Model:                           6
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                 3659.6674    984.371      3.718      0.000    1721.172    5598.163
marketing_cost               4.5785      0.171     26.797      0.000       4.242       4.915
customer_ratings           547.0027     55.782      9.806      0.000     437.152     656.853
number_of_trips              0.4177      0.278      1.503      0.134      -0.130       0.965
poor_weather_index        1.855e+04   1461.863     12.691      0.000    1.57e+04    2.14e+04
Holiday_week              6802.3234    619.101     10.987      0.000    5583.144    8021.503
percent_female_customers   -15.5571     12.302     -1.265      0.207     -39.783       8.668
==============================================================================
Omnibus:                        1.354   Durbin-Watson:                   1.869
Prob(Omnibus):                  0.508   Jarque-Bera (JB):                1.134
Skew:                           0.154   Prob(JB):                        0.567
Kurtosis:                       3.094   Cond. No.                     5.53e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""